/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AgentHostSidRouteImport } from './routes/agent-host.$sid'
import { Route as CaptureSidRouteImport } from './routes/capture.$sid'
import { Route as OrgSettingsRouteImport } from './routes/org.settings'
import { Route as ReplaySidRouteImport } from './routes/replay.$sid'
import { Route as SandboxErpRouteImport } from './routes/sandbox.erp'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as TutorSidRouteImport } from './routes/tutor.$sid'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as WorkmapsIndexRouteImport } from './routes/workmaps.index'
import { Route as WorkmapsIdRouteImport } from './routes/workmaps.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHostSidRoute = AgentHostSidRouteImport.update({
  id: '/agent-host/$sid',
  path: '/agent-host/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureSidRoute = CaptureSidRouteImport.update({
  id: '/capture/$sid',
  path: '/capture/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaySidRoute = ReplaySidRouteImport.update({
  id: '/replay/$sid',
  path: '/replay/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxErpRoute = SandboxErpRouteImport.update({
  id: '/sandbox/erp',
  path: '/sandbox/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSidRoute = TutorSidRouteImport.update({
  id: '/tutor/$sid',
  path: '/tutor/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkmapsIndexRoute = WorkmapsIndexRouteImport.update({
  id: '/workmaps/',
  path: '/workmaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkmapsIdRoute = WorkmapsIdRouteImport.update({
  id: '/workmaps/$id',
  path: '/workmaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/signup': typeof SignupRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/replay/$sid': typeof ReplaySidRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workmaps/$id': typeof WorkmapsIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workmaps/': typeof WorkmapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/signup': typeof SignupRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/replay/$sid': typeof ReplaySidRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workmaps/$id': typeof WorkmapsIdRoute
  '/sessions': typeof SessionsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workmaps': typeof WorkmapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/signup': typeof SignupRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/replay/$sid': typeof ReplaySidRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workmaps/$id': typeof WorkmapsIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workmaps/': typeof WorkmapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/signup'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/replay/$sid'
    | '/sandbox/erp'
    | '/sessions/$id'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workmaps/$id'
    | '/sessions/'
    | '/workflows/'
    | '/workmaps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/signup'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/replay/$sid'
    | '/sandbox/erp'
    | '/sessions/$id'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workmaps/$id'
    | '/sessions'
    | '/workflows'
    | '/workmaps'
  id:
    | '__root__'
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/signup'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/replay/$sid'
    | '/sandbox/erp'
    | '/sessions/$id'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workmaps/$id'
    | '/sessions/'
    | '/workflows/'
    | '/workmaps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostsRoute: typeof CostsRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
  SignupRoute: typeof SignupRoute
  AgentHostSidRoute: typeof AgentHostSidRoute
  CaptureSidRoute: typeof CaptureSidRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  ReplaySidRoute: typeof ReplaySidRoute
  SandboxErpRoute: typeof SandboxErpRoute
  SessionsIdRoute: typeof SessionsIdRoute
  TutorSidRoute: typeof TutorSidRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkmapsIdRoute: typeof WorkmapsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkmapsIndexRoute: typeof WorkmapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-host/$sid': {
      id: '/agent-host/$sid'
      path: '/agent-host/$sid'
      fullPath: '/agent-host/$sid'
      preLoaderRoute: typeof AgentHostSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$sid': {
      id: '/capture/$sid'
      path: '/capture/$sid'
      fullPath: '/capture/$sid'
      preLoaderRoute: typeof CaptureSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$sid': {
      id: '/replay/$sid'
      path: '/replay/$sid'
      fullPath: '/replay/$sid'
      preLoaderRoute: typeof ReplaySidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/erp': {
      id: '/sandbox/erp'
      path: '/sandbox/erp'
      fullPath: '/sandbox/erp'
      preLoaderRoute: typeof SandboxErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$sid': {
      id: '/tutor/$sid'
      path: '/tutor/$sid'
      fullPath: '/tutor/$sid'
      preLoaderRoute: typeof TutorSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workmaps/': {
      id: '/workmaps/'
      path: '/workmaps'
      fullPath: '/workmaps/'
      preLoaderRoute: typeof WorkmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workmaps/$id': {
      id: '/workmaps/$id'
      path: '/workmaps/$id'
      fullPath: '/workmaps/$id'
      preLoaderRoute: typeof WorkmapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostsRoute: CostsRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
  SignupRoute: SignupRoute,
  AgentHostSidRoute: AgentHostSidRoute,
  CaptureSidRoute: CaptureSidRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  ReplaySidRoute: ReplaySidRoute,
  SandboxErpRoute: SandboxErpRoute,
  SessionsIdRoute: SessionsIdRoute,
  TutorSidRoute: TutorSidRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkmapsIdRoute: WorkmapsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkmapsIndexRoute: WorkmapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
